# Generated file by Solital Framework

# Set configurations in PHP Security Password component
password:
  algorithm: default # default - argon2 - argon2d
  cost: 10
  memory_cost: ''
  time_cost: ''
  threads: ''
  crypt_type: openssl
  wait_microseconds: 25000

# Set authentication route
auth:
  auth_dashboard_url: /dashboard
  auth_login_url: /auth