# Generated file by Solital Framework

# Set configurations in PHP Security Password component
password:
  algorithm: default # default - argon2 - argon2d
  cost: 12
  memory_cost: 65536
  time_cost: 4
  threads: 1
  crypt_type: openssl
  wait_microseconds: 25000

# Set authentication route
auth:
  auth_dashboard_url: /dashboard
  auth_login_url: /auth