#!/usr/bin/env php
<?php

require_once 'vendor/autoload.php';

use SebastianBergmann\Environment\Console;
use Solital\Core\Console\Command;
use Solital\Core\Console\TableBuilder;
use Solital\Core\Console\ProgressBar\ProgressBar;
use Solital\Core\Console\ProgressBar\ProgressBarStyle;
use Solital\Core\Console\InputOutput;
use Solital\Core\Console\Output\ColorsEnum;
use Solital\Core\Console\Output\ConsoleOutput;
use Solital\Core\Console\tests\ExtendCommands\{ExtendedCommandsTest, OtherExtendComandTest};

$classes = [ExtendedCommandsTest::class, OtherExtendComandTest::class];
$cmd = new Command($classes);
$res = $cmd->read($argv, $argv);

print_r($res);
exit;

## JOB STATUS --------------------------------

//ConsoleOutput::banner("Debug", 45)->print()->break();

/* ConsoleOutput::debugMessage("Debug", color: 49)->print()->break(true);
ConsoleOutput::status("job", fn () => true, ColorsEnum::YELLOW)->printStatus(); */

## INPUT-OUTPUT --------------------------------

/* $input_output = new InputOutput();
$input_output->color(ColorsEnum::GREEN);
$input_output->confirmDialog('What you want?', 'Y', 'N', false);
$input_output->confirm(function () {
    echo "aceito" . PHP_EOL;
});
$input_output->refuse(function () {
    echo "recusado" . PHP_EOL;
}); */


/* function readline_terminal()
{
    $pwd = shell_exec('C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe -Command "$Password=Read-Host -assecurestring \"Please enter your password\" ; $PlainPassword = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto([System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($Password)) ; echo $PlainPassword;"');
    $pwd = explode("\n", $pwd);
    $pwd = $pwd[0];
    echo "You have entered the following password: $pwd\n";
}
$pass = readline_terminal(); */

/* $input_output = new InputOutput();
$input_output->color(ColorsEnum::GREEN);
$input_output->dialog('Enter a string: ');
$input_output->action(function ($message) {
    echo $message . PHP_EOL;
}); */

/* $input_output = new InputOutput();
$input_output->color(ColorsEnum::GREEN);
$password = $input_output->password("Enter the password");
echo $password; */

## TABLE --------------------------------

/* $headers = ['name', 'age'];
$array = [
    ['brenno', '22 ']
];

(new TableBuilder())->getTableRows($array, $headers); */

/* $pepole = [
    'Mirco Dellarovere' => 'Artista',
    'Nino Pepe' => 'Attore',
    'Zoe Yan' => 'Futurista',
    'Mino' => 'Elettricista'
];

TableBuilder::formattedArray($pepole); */

## NEW PROGRESSBAR --------------------------------

/* $progressbarstyle = new ProgressBarStyle("Downloading", "green", "Kb", 16);
$progressbar = new ProgressBar($progressbarstyle, 1000);

//$progressbar->pauseProgressbar();

for ($i = 0; $i < $progressbar->GetInitialMax(); $i++) {
    $progressbar->step();
    //$progressbar->stepBy(1);
    //$progressbar->stepTo(2184);

    usleep(1000);
}

//$progressbar->resetProgressbar();
$progressbar->terminateProgressbar(); */